### ISSUE TITLE
Make Debian package

### ISSUE THREAD

**Issue by pastly** [pastly/simple-bw-scanner#101]

**Comment by juga0** [comment]
Updating last comment: this is in milestone ``deployment``.

I found a trac ticket related to this: https://trac.torproject.org/projects/tor/ticket/17275

Current status is: package is prepared, it's waiting only for new ``stem`` relase.

**Comment by juga0** [comment]
Changing this issue to milestone 1.0 must, since it was mentioned is needed to have a MVP in https://trac.torproject.org/projects/tor/wiki/org/meetings/2018NetworkTeamHackfestSeattle/sbws

**Comment by juga0** [comment]
Moving this to trac, since there're other related tickets there

**Comment by juga0** [comment]
For future reference, the trac ticket is: https://trac.torproject.org/projects/tor/ticket/26848
