### ISSUE TITLE
Perform downloads over HTTP with no security

### ISSUE THREAD

**Issue by pastly** [pastly/simple-bw-scanner#108]

**Comment by pastly** [comment]
# Python library:  [Requests](http://docs.python-requests.org/en/master/)

- Debian Jessie has [Requests 2.4.3](https://packages.debian.org/jessie/python3-requests)
- Debian Stresh has [2.12.4](https://packages.debian.org/stretch/python3-requests)
- SOCKS5 support in Requests was [added in 2.10](http://docs.python-requests.org/en/master/user/advanced/#socks)
- Tor supports HTTPTunnelPort[ as of 0.3.2.1-alpha](https://blog.torproject.org/tor-0321-alpha-released-support-next-gen-onion-services-and-kist-scheduler), and it can be used to tunnel HTTPS (might have been common knowledge to everyone else)

```bash
cranium:~ mtraudt$ grep HTTPTunnelPort /usr/local/etc/tor/torrc
HTTPTunnelPort 3128
cranium:~ mtraudt$ export HTTP_PROXY="http://127.0.0.1:3128"
cranium:~ mtraudt$ export HTTPS_PROXY="http://127.0.0.1:3128"
cranium:~ mtraudt$ curl https://wtfismyip.com/text
178.17.170.135
cranium:~ mtraudt$ # That's not my IP, it's 50BD3C2C70050A999BD423EB23CDAE21F2214E02
```

**Comment by teor2345** [comment]
> > Debian Jessie has Requests 2.4.3
> 
> That's old stable. Probably bwauths running it couldn't not upgrade to stretch because Torflow wouldn't be compatible with newer versions of python libraries

Some bwauths don't run Debian.

As of today (April 26, 2018), Jessie is no longer fully supported. It will have long term support until April 2020.
https://www.debian.org/releases/
https://www.debian.org/releases/jessie/

I don't think we should make decisions based on dependency versions in old releases.
And we can't keep supporting the dependencies of Torflow.
(Operators can spin up another machine, a VM, or a virtual environment.)

Let's move forward with the current stable releases of Debian and the other OSs used by the bandwidth authority operators.
