### ISSUE TITLE
Gather all global constants, and make their naming consistent

### ISSUE THREAD

**Issue by pastly** [pastly/simple-bw-scanner#116]
In `sbws/globals.py` we have 

- `G_PKG_DIR` where the G was supposed to stand for global
- and other ALL_CAPS constants

In `sbws/__init__.py` we have

- `version`
- `res_proto_ver`
- `wire_proto_ver`

---

- [ ] pick one file or the other.
- [ ] Pick a naming scheme. `G_FOO` or `FOO` is what I'd prefer.
- [ ] If we change the name or location of `version`, we need to update `setup.py` and `docs/source/conf.py` and (if we've merged @juga0's V3BwHeader PR) `sbws/lib/v3bwfile.py`

**Comment by teor2345** [comment]
> In sbws/globals.py we have
> 
> G_PKG_DIR where the G was supposed to stand for global
> and other ALL_CAPS constants
> In sbws/__init__.py we have
> 
> version
> res_proto_ver
> wire_proto_ver
In general, we should try to minimise globals. Versions are an exception.
>  pick one file or the other.
What do other packages do?
>  Pick a naming scheme. G_FOO or FOO is what I'd prefer.
FOO is standard, no need to use the G_.
>  If we change the name or location of version, we need to update setup.py and docs/source/conf.py and (if we've merged @juga0's V3BwHeader PR) sbws/lib/v3bwfile.py

**Comment by pastly** [comment]
(Primarily notes to self so I know what  I want to do when I get around to this)

The ALL_CAPS globals in `sbws/globals.py` are

- G_PKG_DIR
- MIN_REQ_BYTES
- MAX_REQ_BYTES
- SOCKET_TIMEOUT

MAX_REQ_BYTES is probably getting replaced in the process of implementing #124. MIN_REQ_BYTES could too. SOCKET_TIMEOUT could be a config option.

I'll rename G_PKG_DIR to PKG_DIR.

The constants in `sbws/__init__.py` are

- version
- res_proto_ver
- wire_proto_ver

wire_proto_ver is going away with the switch to HTTP. res_proto_ver I'll RENAME. version I'll RENAME.

I will move all constants to `sbws/__init__.py`. We can consider moving the 3 functions in `sbws/globals.py` at a later time. I think having global constants and functions in `__init__.py` is more common.
