### ISSUE TITLE
Add useful information in sbws header lines

### ISSUE THREAD

**Issue by teor2345** [pastly/simple-bw-scanner#119]
We should think about adding some more useful fields in sbws v3bw file header lines:
* when the scanner started
* the time of the earliest measurement used to generate the file
* helper exits (maybe, could have security implications)

And any other useful information.

I think the times would be useful for debugging 1.0. Other fields we could add later.

**Comment by teor2345** [comment]
We should also remember that Tor has a 512 byte limit for header lines.

**Comment by juga0** [comment]
i could add the two first ones. 3rd with an option. Then we see...
