### ISSUE TITLE
Document Tor's ClientRejectInternalAddresses option

### ISSUE THREAD

**Issue by teor2345** [pastly/simple-bw-scanner#122]
This is a follow-up to #90, which I can't reopen because I don't have the permissions.

If clients set ClientRejectInternalAddresses, and the exit sets ExitPolicyRejectPrivate 0, clients can connect to 127.0.0.1 on an exit.

**Comment by pastly** [comment]
I'm closing this because sbws no longer uses helper relays and I don't see a scenario where we want to actually have exits connect to 127.0.0.1 for us.
