### ISSUE TITLE
Reevaluate how to pin a self-signed server cert

### ISSUE THREAD

**Issue by pastly** [pastly/simple-bw-scanner#127]
In my draft proposal, I said sbws should take a fingerprint and verify the certificate it receives from the server matches.

Requests does not seem to make doing that easy. 

According to [the docs](http://docs.python-requests.org/en/master/user/advanced/#ssl-cert-verification), We can either

- set `verify` to True (default)
- set `verify` to False
- set `verify` to a string that is a local file containing one or more certificates to trust (if I understand correctly)

If in the sbws config we take a path to a local file containing the server's certificate, we can pin a cert that way.

https://stackoverflow.com/questions/26479039/python-requests-direct-pem-pinning-with-self-signed-cert#26487178

**Comment by teor2345** [comment]
We could take a per-server "verify" preference, and pass it straight to Requests.

**Comment by pastly** [comment]
Yes! Exactly. I'd probably call it `verify_server_cert`, but yes.

```
# verify = true to be explicit, but this would be the default
[destinations.foo]
url = https://abc.com/1G
verify_server_cert = on

# omg so dangerous
[destinations.bar]
url = https://xyz.com/1G
verify_server_cert = off

# pinned cert
[destinations.baz]
url = https://123.com/1G
verify_server_cert = ${paths:sbws_home}/certs/baz.cert

# non-https, it would be fatal config error to give verify_server_cert
[destinations.aaaaaaa]
url = http://456.com/1G
```
