### ISSUE TITLE
Stop assuming that Tor will download a consensus flavour that contains exit policies

### ISSUE THREAD

**Issue by teor2345** [pastly/simple-bw-scanner#144]
We spend a lot of time messing with tor options to make sure it has a consensus flavour that contains an exit policy. Instead, let's just look for the exit policy in the consensus, and if it isn't there, in the microdescriptors.

This will save us from a whole lot of future bugs where people deploy with the wrong torrc options.

For details, see:
https://trac.torproject.org/projects/tor/ticket/25979#comment:4

**Comment by pastly** [comment]
Thank you for helping investigate, @teor2345.

Sbws scanners will be launching their own Tor processes soon, but this is still very good info for telling me exactly what torrc options are needed.
