### ISSUE TITLE
GETINFO ns/all bandwidth lines do not contain the unmeasured flag

### ISSUE THREAD

**Issue by teor2345** [pastly/simple-bw-scanner#145]
There's a comment about is_unmeasured being broken in:
https://github.com/pastly/simple-bw-scanner/blob/master/sbws/lib/relaylist.py#L63

Stem's get_network_statuses() method uses GETINFO ns/all. GETINFO ns/all doesn't have the Unmeasured flag, but GETINFO dir/status-vote/current/consensus does.

You'll need to implement a wrapper like https://stem.torproject.org/_modules/stem/control.html#Controller.get_network_statuses

GETINFO ns/all could be better documented, too:
https://gitweb.torproject.org/torspec.git/tree/control-spec.txt#n611
We will fix this as part of https://trac.torproject.org/projects/tor/ticket/24110

**Comment by pastly** [comment]
> Stem's get_network_statuses() method uses GETINFO ns/all. GETINFO ns/all doesn't have the Unmeasured flag, but GETINFO dir/status-vote/current/consensus does.
> 
> You'll need to implement a wrapper like https://stem.torproject.org/_modules/stem/control.html#Controller.get_network_statuses

Did you mean to link to `get_network_statuses` here? As you said, it uses `GETINFO ns/all`

**Comment by teor2345** [comment]
You'll need to implement a wrapper like the code of https://stem.torproject.org/_modules/stem/control.html#Controller.get_network_statuses
But for GETINFO dir/status-vote/current/consensus rather than ns/all.
