### ISSUE TITLE
Logo proposal: Simple Bandwidth Scanner

### ISSUE THREAD

**Issue by baranpirincal** [pastly/simple-bw-scanner#148]
Good night, I saw that your project has no logo design yet. My main purpose is supporting open source projects in field of graphic design. If you interested i can contribute on your project with making logo design. We can discuss about design decisions. I am waiting your feedback! Have a nice day! 

Best Regards,
Baran Pirincal
Visual Communication Designer

**Comment by pastly** [comment]
Thank you for the offer.

The Tor Project has a UX team that we would consult first if we decide we would like a logo.

I hope you have a wonderful day.
