### ISSUE TITLE
Circuits and downloads need to timeout

### ISSUE THREAD

**Issue by pastly** [pastly/simple-bw-scanner#151]
I just saw a download take 900+ seconds to complete. That's stupid.

And circuits are taking 2+ minutes to fail, even though I've set `CircuitBuildTimeout 10` and `LearnCircuitBuildTimeout 0`.

**Comment by teor2345** [comment]
The CircuitBuildTimeout is only for building a circuit.

You probably also want to set:
CircuitStreamTimeout
SocksTimeout

The maximum timeout will probably be something like SocksTimeout + CircuitBuildTimeout + 3*CircuitStreamTimeout in pathological cases.

**Comment by pastly** [comment]
Made a request timeout after 10s of not receiving any new data in 3e74ddeb5d50c17bd7fcee892370adfb691b9790

Made circuits actually timeout after 10s with dc63ad05bb78bd81d68046688e6f08a717150b9f. See the commit message for why this was so effing hard.
