### ISSUE TITLE
sbws should never provide a weight that is greater than the relay's bandwidth rate

### ISSUE THREAD

**Issue by teor2345** [pastly/simple-bw-scanner#155]
Relays advertise a maximum bandwidth they will handle, which in their torrcs is either RelayBandwidthRate, RelayBandwidthBurst, or MaxAdvertisedBandwidth.

They then put this in the bandwidth line of their descriptors as bwrate and bwburst.

Torflow partitions relays by bwrate, so its weights roughly correspond to their bandwidth rates.

sbws doesn't have partitions, so it should either:
1. choose exits using min(bwrate, bwburst)
2. limit weights using min(bwrate, bwburst)

I suggest option 2, because it responds to rate changes quickly. We might also want to consider option 1, because there is no reason to use a fast exit on a slow relay.

For details, see:
https://trac.torproject.org/projects/tor/ticket/8494#comment:6

**Comment by pastly** [comment]
Does this still make sense in a world where weight doesn't translate particularly well to bandwidth? Such as a world where we scale?

**Comment by teor2345** [comment]
> Does this still make sense in a world where weight doesn't translate particularly well to bandwidth? Such as a world where we scale?

Yes.

sbws should limit bandwidths based on {Relay,}Bandwidth{Rate,Burst} or MaxAdvertisedBandwidth.
If a relay has specified a bandwidth limit, it should end up with a weight/rank that is similar to the weight/rank of other relays with that bandwidth.
Otherwise, MaxAdvertisedBandwidth is useless.

Scaling doesn't change this requirement.

But scaling may mean that the easiest time to impose the limit is immediately after we get a measurement.

**Comment by juga0** [comment]
I can work on this, but would like to reuse the Relay class in https://github.com/pastly/simple-bw-scanner/pull/174/commits/50c15f1cd14b266eaa14465f0262a7515b5a3a8b#diff-185bfbf5b7aeee8738d3cdcdfded5b05R16

**Comment by pastly** [comment]
Closed with #191
