### ISSUE TITLE
Properly check for or automatically install the right version of stem

### ISSUE THREAD

**Issue by pastly** [pastly/simple-bw-scanner#162]
We now depend on a feature added in stem 1.6.0-dev. See my [commit message](https://github.com/pastly/simple-bw-scanner/commit/1102cbd5b56ef144c05d76aa04485c14b4fc85c9).

I can't quickly figure out how to specify in `setup.py` that we need to download stem from git.tpo.

It would be great if we could convince @atagar to release 1.7.0 :)

**Comment by teor2345** [comment]
This is how pip can be configured to install from git:
https://stackoverflow.com/questions/16584552/how-to-state-in-requirements-txt-a-direct-github-source#16584935

Apparently this is possible in setup.py as well:
https://stackoverflow.com/questions/3472430/how-can-i-make-setuptools-install-a-package-thats-not-on-pypi

**Comment by pastly** [comment]
While I don't like having to have pip `git clone` stem (or have the user `git clone` stem themself), it has been working and should continue to work until there's a new version of stem.
