### ISSUE TITLE
Use the latest scanner result time for the bandwidth file timestamp

### ISSUE THREAD

**Issue by teor2345** [pastly/simple-bw-scanner#169]
The bandwidth file spec uses the file creation time for the initial timestamp. It should use the latest scan time:
https://trac.torproject.org/projects/tor/ticket/26155

Once the spec is fixed, we need to update sbws with the new fields:
* fix initial Timestamp so it is the latest result time
* optional: add file_created (the file creation time)
* optional: add latest_bandwidth (a copy of the initial Timestamp in human-readable format)

**Comment by teor2345** [comment]
This needs to be fixed for 1.0, otherwise scanner statuses won't work.

Also: updated the description to show optional fields.

**Comment by juga0** [comment]
WIP in https://github.com/pastly/simple-bw-scanner/compare/master...juga0:issue169

**Comment by teor2345** [comment]
These are spec questions, so I answered them on the spec ticket:
https://trac.torproject.org/projects/tor/ticket/26155#comment:8

I recommend you wait until the spec is merged before making changes to sbws.

**Comment by juga0** [comment]
@pastly, i'm changing bw lines unix timestamp to iso in generate, to follow spec.
Should we change also change all the unix timestamp in the results so that they're also easy to ready and we use same format in all the code (except the 1st line in bw file)?.
We don't need to deal with timezones, since we're still using utc in iso dates.

**Comment by pastly** [comment]
> Should we change also change all the unix timestamp in the results so that they're also easy to read

Sure

> and we use same format in all the code

Sounds like a lot of work, but maybe.

**Comment by juga0** [comment]
After working more on branch issue169, we can leave results in unix timestamp.
If we change them, probably we need to change many other parts of the code.

**Comment by juga0** [comment]
I see now your answer now, created #171

**Comment by juga0** [comment]
This issue has been fixed after merging #175
