### ISSUE TITLE
Add "Relay" abstraction layer

### ISSUE THREAD

**Issue by pastly** [pastly/simple-bw-scanner#180]
Currently when we have a "relay" in sbws, we have a RouterStatusEntryV3 from stem. (Fun fact: In the RelayPrioritizer we temporarily add a priority property to this, but delete it before returning the relay.)

This has worked fine ... until now. Now we want to have access to a relay's bandwidth line in its full descriptor (#155) and we want this for the Minimally Viable Product (MVP). It would also be nice to be able to get the ed25519 identity (like @juga has done in #174), but this is not needed for the MVP.

Add a Relay class that abstracts away all the different sources of information from Tor into one unified object that only has the properties we use.

**Comment by juga0** [comment]
Even if #174 is not needed for a MVP, the patch is not very big and is done and if the Relay class created there can be used for the Relay class proposed here, then i think it should just be (merged) and used.
Otherwise we should see what else that class needs and where it should go.

**Comment by pastly** [comment]
Done
