### ISSUE TITLE
TypeError install sbws in python 3.4.2

### ISSUE THREAD

**Issue by juga0** [pastly/simple-bw-scanner#194]
Installing ``sbws`` by ``pip install -e .`` or ``python setup.py install`` gives this error:

```
Traceback (most recent call last):
  File "setup.py", line 45, in <module>
    version=find_version(),
  File "setup.py", line 38, in find_version
    if "__version__" in line.strip():
TypeError: Type str doesn't support the buffer API
```

**Comment by pastly** [comment]
I'm curious why you're trying 3.4.2. Is that what your OS provides?

`pyenv` suggests that the latest version in the 3.4 series is 3.4.8. 

```
pyenv install --list | grep -F '  3.4.'
  3.4.0
  3.4.1
  3.4.2
  3.4.3
  3.4.4
  3.4.5
  3.4.6
  3.4.7
  3.4.8
```

And [Travis is using 3.4.6](https://travis-ci.org/pastly/simple-bw-scanner/jobs/392535797#L434)

**Comment by juga0** [comment]
> I'm curious why you're trying 3.4.2. Is that what your OS provides?

yes, it is the version in Debian jessie (oldstable) [0]

Though now updating which are the Python versions that the bwauths are
runing [1], the earliest version we might need to support 3.4.5.

I'll change to that one and if this error doesn't happen, i guess we can
close it.

[0]
https://github.com/pastly/simple-bw-scanner/wiki/Existing-sbws-infrastructure#juga-1
[1]
https://github.com/pastly/simple-bw-scanner/wiki/Information-regarding-sbws's-target-user-base#python-3

**Comment by juga0** [comment]
Now i'm realizing that anyway RH 6 won't be able to run sbws because of stem version [0]
So maybe we don't need to support python 3.4 at all...

[0] https://github.com/pastly/simple-bw-scanner/wiki/Information-regarding-sbws's-target-user-base#stem

**Comment by juga0** [comment]
I think we could solve this supporting only python versions from 3.4.5. If you agree, i can modify to setup.py:
    python_requires='>=3.4.5',

**Comment by pastly** [comment]
Yes

On June 25, 2018 5:17:15 AM EDT, juga0 <notifications@github.com> wrote:
>I think we could solve this supporting only python versions from 3.4.5.
>If you agree, i can modify to setup.py:
>    python_requires='>=3.4.5',
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pastly/simple-bw-scanner/issues/194#issuecomment-399886553

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by juga0** [comment]
ok, will just wait #203  to confirm that 3.4.5 is the lower we will support

**Comment by juga0** [comment]
Since it's such as small change, created PR, we can address #203 in other moment.
