### ISSUE TITLE
Determine what python versions have buggy lru_cache

### ISSUE THREAD

**Issue by pastly** [pastly/simple-bw-scanner#198]
and tell @atagar. Then he'll patch stem and make a release.

Example tracebacks:

```
[2018-05-07 19:47:42,143] [sbws.lib.relaylist] [ERROR] Got that KeyError in stem again...: (<stem.exit_policy.MicroExitPolicy object at 0x7f8de6438ba8>,)
Traceback (most recent call last):
  File "/home/pastly/src/simple-bw-scanner/sbws/lib/relaylist.py", line 112, in exits_can_exit_to
    if policy is not None and policy.can_exit_to(port=port):
  File "/home/pastly/src/simple-bw-scanner/venv-editable/lib/python3.5/site-packages/stem/exit_policy.py", line 285, in can_exit_to
    if not self.is_exiting_allowed():
KeyError: (<stem.exit_policy.MicroExitPolicy object at 0x7f8de6438ba8>,)
```

```
[2018-05-07 06:49:45,995] [sbws.lib.relaylist] [ERROR] Got that KeyError in stem again...: (<stem.exit_policy.MicroExitPolicy object at 0x7f8de7ef0a90>, <object object at 0x7f8e1f1f7080>, ('port', 443))
Traceback (most recent call last):                                                                                                            
  File "/home/pastly/src/simple-bw-scanner/sbws/lib/relaylist.py", line 112, in exits_can_exit_to                                             
    if policy is not None and policy.can_exit_to(port=port):                                                                                  
KeyError: (<stem.exit_policy.MicroExitPolicy object at 0x7f8de7ef0a90>, <object object at 0x7f8e1f1f7080>, ('port', 443))                     
```

I was running Python 3.5.3 and told sbws to use 6 measurement threads.

Python bugs (both marked as "fixed") that @atagar suggested might be related:

- [functools.lru_cache raises KeyError](https://bugs.python.org/issue25295)
- [lru_cache is not threadsafe](https://bugs.python.org/issue28969)

It looks like the C implementation of lru_cache was added to Python [here](https://github.com/python/cpython/commit/1c858c352b8c11419f79f586334c49378726dba8#diff-76af87b8b135d9212a62a8fa7fda7a6a). This would suggest to me that the bug does not exist in 3.4.X.

**Comment by pastly** [comment]
I wrote a script that approximates sbws behavior reasonably well I think (at least regarding this bug).

I'm going to try running this with various versions of Python. I still think sbws should be run with various versions of Python.

```
$ cat torrc
SocksPort 0
ControlPort 16893
UseMicrodescriptors 0
Socks5Proxy 127.0.0.1:2343
DataDirectory tor
```
```
$ cat test.py
#!/usr/bin/env python3
from stem.control import Controller
from stem.process import launch_tor
from multiprocessing.dummy import Pool
import time
from random import randint, choice
from datetime import datetime

CTRL_PORT = 16893
NUM_THREADS = 6
UPDATE_EVERY = 300  # seconds


def _get_controller():
    c = Controller.from_port(port=CTRL_PORT)
    c.authenticate()
    return c


def _launch_tor():
    proc = launch_tor(
        torrc_path='./torrc',
        take_ownership=True)
    return proc


def dispatch_worker(cont, fp):
    desc = cont.get_server_descriptor(fp, default=None)
    if not desc:
        print('WARN couldn\'t get desc for', fp[0:8])
        return
    exit_policy = desc.exit_policy
    time.sleep(randint(6*3, 10*3))
    can_exit = exit_policy.can_exit_to('144.217.254.208', 80)
    return fp, desc.nickname, can_exit


def callback(*a):
    print(datetime.utcnow(), *a)


def _need_update_descs(last_update):
    if time.time() < last_update + UPDATE_EVERY:
        return False
    return True


def _update_descs(cont):
    print('IN1FO Updating descriptors')
    descs = [d for d in cont.get_server_descriptors()]
    descs = [d for d in descs if d.exit_policy.is_exiting_allowed()]
    fps = [d.fingerprint for d in descs]
    return descs, fps, time.time()


def main(cont):
    pool = Pool(NUM_THREADS)
    pending = []
    descs, fps, last_update = _update_descs(cont)
    while True:
        if _need_update_descs(last_update):
            descs, fps, last_update = _update_descs(cont)
        async_ret = pool.apply_async(
            dispatch_worker, [cont, choice(fps)], {}, callback)
        pending.append(async_ret)
        while len(pending) >= NUM_THREADS:
            # print('DEBUG sleeping until not too many pending')
            time.sleep(5)
            pending = [r for r in pending if not r.ready()]


if __name__ == '__main__':
    _launch_tor()
    cont = _get_controller()
    main(cont)
```

**Comment by juga0** [comment]
Are you already running this?, 
with which python versions?,
the goal is to find a way to reproduce it so that @atagar can fix it?
if it's a python bug, i wonder if @atagar would be able to patch it or we would need to report a bug in python anyway.
Is there already and stem ticket for this?

**Comment by pastly** [comment]
> Are you already running this?,
> with which python versions?,

I'm running the script I pasted above with 3.4.8, 3.5.5, and 3.6.5.

> the goal is to find a way to reproduce it so that @atagar can fix it?

We already know half the fix. The half we know is that we should change [the importing of lru_cache here](https://gitweb.torproject.org/stem.git/tree/stem/exit_policy.py#n80) to import Python's lru_cache in most cases, but for certain Python versions (that have yet to be determined)   import stem's lru_cache instead.

> if it's a python bug, i wonder if @atagar would be able to patch it or we would need to report a bug in python anyway.

It's probably a Python bug, but I'm lacking either motivation or knowledge (or both) to diagnose or fix it in Python's C code (or both). I don't think we should try.

> Is there already and stem ticket for this?

Nope

**Comment by juga0** [comment]
> I'm running the script I pasted above with 3.4.8, 3.5.5, and 3.6.5.

then there seem to be no need i run it, right?
I'm running sbws with several versions.

>> the goal is to find a way to reproduce it so that @atagar can fix it?
> 
> We already know half the fix. The half we know is that we should change [the importing of lru_cache here](https://gitweb.torproject.org/stem.git/tree/stem/exit_policy.py#n80) to import Python's lru_cache in most cases, but for certain Python versions (that have yet to be determined)   import stem's lru_cache instead.

oh, i see, then the import could be already changed when the version is
3.5.3. Maybe it is not too critical that we fix it for the rest of the
versions when sbws is in production

>> if it's a python bug, i wonder if @atagar would be able to patch it or we would need to report a bug in python anyway.
> 
> It's probably a Python bug, but I'm lacking either motivation or knowledge (or both) to diagnose or fix it in Python's C code (or both). I don't think we should try.

I meant to report the ticket, not to fix it, but it's fine if we don't
report it either

>> Is there already and stem ticket for this?

then i'm going to create one

**Comment by juga0** [comment]
I created https://trac.torproject.org/projects/tor/ticket/26412.
Probably better to comment findings there.

**Comment by pastly** [comment]
I also have not been able to reproduce the KeyError with a recent version of sbws that uses descriptors instead of microdescriptors.

I'm going to now switch to an old version of sbws. Even though it may no longer be important to us, if we can recreate it that would be helpful to atagar.

**Comment by pastly** [comment]
I'm running sbws v0.4.0 (which uses exit policies from microdescriptors) with python 348, 353, and 365 now.

**Comment by pastly** [comment]
Python 353 is already hitting the KeyError.

I'm going to keep 348 and 365 running for now and try another python version in the 35X series.

**Comment by juga0** [comment]
> I'm going to keep 348 and 365 running for now and try another python version in the 35X series. 

ok, let me know if you would need i also run them, for now i'll keep
running the master version then.

**Comment by pastly** [comment]
Regarding the 35X series: I believe the bug was fixed between 353 and 354. 352 and 353 both produce KeyErrors almost immediately but 354 didn't do it within 2 hours.

I'll update the trac ticket with this information and try older versions in the 34X and 36X series

**Comment by pastly** [comment]
This doesn't affect us anymore because we use full server descriptors now, those don't seem to cause the issue, and I've reported results to atagar https://trac.torproject.org/projects/tor/ticket/26412#comment:5

Considering this closed.
