### ISSUE TITLE
sbws canonical repo in tpo?

### ISSUE THREAD

**Issue by juga0** [pastly/simple-bw-scanner#200]
I don't know if there has been a decision on whether to use Trac or Github for sbws's issues [0].
I think that if sbws ends up being the default scanner run by bwauths, the canonical sbws repo should be in Tor Project infrastructure, so that Tor Project can maintain it in the long term. 
We could still work on issues/PRs in Github, as it's done in gh/torproject.
@pastly if you agree, i/you can create an issue in trac.tpo to create the repo, otherwise we can continue working here.
[0] https://trac.torproject.org/projects/tor/wiki/org/meetings/2018NetworkTeamHackfestSeattle/sbws

**Comment by pastly** [comment]
https://gitweb.torproject.org/sbws.git exists.

I think sometime soon we should switch to trac for issues and keep GitHub for PR review and stuff like that.

**Comment by juga0** [comment]
> https://gitweb.torproject.org/sbws.git exists.
i didn't know, perfect, then we can close this ticket.

> I think sometime soon we should switch to trac for issues and keep GitHub for PR review and stuff like that.
yeah, let's do that when we reach 1.0 (or before)
