### ISSUE TITLE
Move (plotting) scripts requiring extra dependencies to other repo?

### ISSUE THREAD

**Issue by juga0** [pastly/simple-bw-scanner#201]
The scripts in ``scripts/tools/`` are useful and we probably will need to write more. 
It would be useful to have them as a separate repo so anyone can run them without needing the rest of sbws code but just the required files.
Also the other way around, bwauths might want to only run sbws, and they don't need those scripts.
Those scripts also require extra dependen that are not install by default, and i don't think we should install them by default in sbws, but then they would not work without them.
This would be specially important if we package sbws for Debian, since the package should manage the dependencies.
@pastly since the code there has been written by you, it's probably you that should create the repo, if you agree

**Comment by juga0** [comment]
> [Tor has a scripts directory](https://gitweb.torproject.org/tor.git/tree/scripts). A lot of the stuff in it is not useful without external dependencies that are not installed by default. For example [this](https://gitweb.torproject.org/tor.git/tree/scripts/codegen/makedesc.py) python script depends on something called `slow_ed25519` and there's an entire directory for coccinelle, which is something I've only ever heard about.

That repo has scripts for other type of stuff, don't think what i
suggest should go there.

i meant to create a repo called for instance ``tor_bw_stats`` where to
put the scripts currently ``tools/scripts`` and all the scripts meant
for graphs related to bw that we might create in the future.

For instance, i missed not to have a repo with the scripts to reproduce
the graphs in https://trac.torproject.org/projects/tor/ticket/25459.
It'd be great if we can share it for instance with @gman999 or tjr, and
they don't need all the rest of ``sbws`` code.
I'm quite sure we'll need to create more graphs in the future.

> Do these scripts end up in the Tor debs? I doubt it, but haven't checked.

same

> I don't think the scripts directory is required to go into a deb, and I don't think it should. 

me neither, not even as part of ``sbws``, so ``sbws`` is "simple" and
only do what it's intended to do.


> I think if people want to run the scripts in the directory, then they will already be willing to clone the repo and will have the knowledge required for installing their dependencies.

i'd prefer to:
```
git clone tor_bw_stats
python setup.py
runmyscript.
```

Without bothering about what i need to get from here or there nor
manually install deps.

> I can better document the dependencies for each script. From memory, it's probably just matplotlib for the plotting script. Would documenting this help? 

Yeah, i think it's only that now, though we might end up with more. If
you agree we put the scripts in a different repo, i can create the
readme, setup.py and all that stuff to make it pretty (if you like) :)

**Comment by pastly** [comment]
I think I understand better now.

I thought you wanted to move the scripts directory entirely (or remove scripts/tools/ entirely) to somewhere else. But you just want to move `plot-v3bw-xy.py` and maybe `v3bw-into-xy.py` into a repo with a bunch of v3bw parsing/plotting/statistics-ing scripts.

That sounds agreeable.

**Comment by pastly** [comment]
I will move scripts to https://github.com/pastly/v3bw-tools

**Comment by pastly** [comment]
I consider this done now. Reopen if you think otherwise.
