### ISSUE TITLE
unit tests: Refactor Results fixtures to reuse in resultdump and v3bwfile

### ISSUE THREAD

**Issue by juga0** [pastly/simple-bw-scanner#216]
As part of the big test refactoring plan, i'd start with the fixtures, in particular Results, since we use them in different tests.

I'd create:
1. fixture with result as dict, as in https://github.com/pastly/simple-bw-scanner/blob/master/tests/unit/lib/test_v3bwfile.py#L45
2. fixture with result as a class, reusing the previous one, as in https://github.com/pastly/simple-bw-scanner/blob/master/tests/unit/lib/test_results.py#L77, but without writing to disk
3. if fixture in disk is needed, i'd reuse the ones in the the commit https://github.com/pastly/simple-bw-scanner/pull/213/commits/ce0af44dace902a908534ce82015887d161a9ea6 and the previous one.

The fixtures in the previous commit, can be moved to a conftest.py one level up and be also reused by integration/confftest.py. Then (persistent)empty_dotsbws in unit and integration conftest.py can then be refactored too.

I already started to do it, but it's quite lot of work, so better ensure that @pastly  agrees with this.

I think this has to be in 1.0, but actually question, do we want 100% test coverage in a MVP?. It's quite lot of work, though i think it should be.

**Comment by teor2345** [comment]
> I think this has to be in 1.0, but actually question, do we want 100% test coverage in a MVP?. It's quite lot of work, though i think it should be.

The minimum viable product has to deploy and run on one public directory authority.
Test coverage contributes to that goal by making the software correct and reliable.

If we focus on testing correctness and reliability, we can do 100% coverage in a later release.

**Comment by pastly** [comment]
> do we want 100% test coverage in a MVP?. It's quite lot of work, though i think it should be.

No I do not want to require 100% coverage for MVP. I agree it might be nice, but I do not think it should be a requirement.

Furthermore, not all coverage is created equal. IIRC, I added 11% coverage just by adding one test that measured a relay. I only exercised the "happy" code paths. This single test did not try to exercise likely troublesome situations. It's better than nothing, but all the code it covers should be covered by more specific unit tests too (In an ideal world; this is not me saying we should add comprehensive unit tests to MVP).

**Comment by pastly** [comment]
I'll come back and leave feedback about your proposed changes soonish.

**Comment by juga0** [comment]
> Furthermore, not all coverage is created equal. IIRC, I added 11% coverage just by adding one test that measured a relay. I only exercised the "happy" code paths. This single test did not try to exercise likely troublesome situations. It's better than nothing, but all the code it covers should be covered by more specific unit tests too (In an ideal world; this is not me saying we should add comprehensive unit tests to MVP).

Yeah, coverage i just other measure, and i agree it is not the most fair one

**Comment by juga0** [comment]
> The minimum viable product has to deploy and run on one public directory authority.
> Test coverage contributes to that goal by making the software correct and reliable.
> 
> If we focus on testing correctness and reliability, we can do 100% coverage in a later release.

right, but how to ensure "correctness and reliability".
I'm doing distracted/stupid mistakes very often, that would have just
been detected with *good* tests.

**Comment by juga0** [comment]
Working on this, reusing what i'm doing for #209
