### ISSUE TITLE
Sbws measures BadExits in the exit position. Is that what it should do?

### ISSUE THREAD

**Issue by pastly** [pastly/simple-bw-scanner#217]
See this relay (**not** the IPredator you're thinking of) https://metrics.torproject.org/rs.html#details/378D79CF8A9C5CA0EF6D9D0815AD01255C834484
![screen shot 2018-06-28 at 13 47 08](https://user-images.githubusercontent.com/9538998/42051333-cda36932-7ad9-11e8-81be-f36d3358cd9a.png)

Sbws saw that it had the exit flag, found a non exit helper, and built a circuit to measure this "iPredator" relay while it is in the exit position.

Should sbws treat relays with both Exit and BadExit as non-exits?

I think yes.

This is a easy change to make, but I'm soliciting feedback.

**Comment by juga0** [comment]
> Sbws saw that it had the exit flag, found a non exit helper, and built a circuit to measure this "IPredator" relay while it is in the exit position.
> 
> Should sbws treat relays with both Exit and BadExit as non-exits?

hmm, why would we measure badexits?,
and why would use them as non-exits?

**Comment by pastly** [comment]
We would measure a bad exit because it's still part of the network and clients will still use it in non-exit positions.

I'm suggesting that since clients use them as non-exits, then sbws should measure them as non-exits.

**Comment by teor2345** [comment]
Yes, BadExits should be treated like middle relays (or guard relays). That's what torflow does.

And this is a 1.0 issue, because it's security-sensitive.

**Comment by juga0** [comment]
Matt Traudt:
> We would measure a bad exit because it's still part of the network and clients will still use it in non-exit positions.
> 
> I'm suggesting that since clients use them as non-exits, then sbws should measure them as non-exits.
> 
I see, sounds good then

**Comment by juga0** [comment]
Closing because fixed by #218
