### ISSUE TITLE
Include file where to write ``generate`` results in the config?

### ISSUE THREAD

**Issue by juga0** [pastly/simple-bw-scanner#91]
I think this can be useful, since dirauths assume the measurements will be in a file. 
Maybe it is included now and i haven't realized, sorry if that is the case.

**Comment by juga0** [comment]
It could be done in a more generic way in case we would have some other option that also overrides config.
If you think that's an option, we can close this ticket and create other

**Comment by pastly** [comment]
I think for now we should just add a path in the example config (which becomes the user's config after running `sbws init`) and if `--output` is given when calling `sbws generate`, it overrides the path in the config.

In the `[paths]` section in `sbws/config.example.ini`, I would add an option such as this:

```
[paths]
v3bw_fname = ${sbws_home}/v3bw
```

I can do this pretty quickly if you want.

**Comment by juga0** [comment]
Matt Traudt:
> I think for now we should just add a path in the example config (which becomes the user's config after running `sbws init`) and if `--output` is given when calling `sbws generate`, it overrides the path in the config.

Sounds good to me

> I can do this pretty quickly if you want.

ok, thanks
